# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    This method creates various NumPy arrays based on the mode.
    Parameters:
      mode (str): The type of array to create. Options are:
        - 'zeros': Creates an array filled with zeros
        - 'ones': Creates an array filled with ones
        - 'full': Creates an array filled with a specified value
        - 'identity': Creates an identity matrix
      shape (tuple): The shape of the array to create
      value: The value to fill the array with when mode is 'full'
    Returns:
      The created NumPy array
    """
    if mode == 'zeros':
        return np.zeros(shape)
    elif mode == 'ones':
        return np.ones(shape)
    elif mode == 'full':
        return np.full(shape, value)
    elif mode == 'identity':
        return np.eye(shape)
    else:
        raise ValueError(f"Unknown mode: {mode}")
    
mode = input("Enter mode: ").strip().lower()

if mode == 'identity':
    shape = int(input("Enter the size of the identity matrix: "))
else:
    shape_input = input("Enter shape (n,m): ")
    shape = tuple(map(int, shape_input.split(',')))

value = None
if mode == 'full':
    value = float(input("Enter the value to fill the array with: "))

array = array_factory(mode, shape, value)
print("Created array:")
print(array)

Created array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [2]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        array1 = np.array(data1)
        array2 = np.array(data2)
        reshaped_array1 = array1.reshape(new_shape)
        combined_dataset = np.vstack((reshaped_array1, array2))
        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

data1_input = input("Enter data1: ")
data1 = list(map(float, data1_input.split(',')))

data2_input = input("Enter data2 as rows separated by ';' and numbers by ',': ")
data2 = [list(map(float, row.split(','))) for row in data2_input.split(';')]

shape_input = input("Enter new shape for data1: ")
new_shape = tuple(map(int, shape_input.split(',')))

try:
    result = secure_reshape_and_stack(data1, data2, new_shape)
    print("Combined dataset:")
    print(result)
except ValueError as e:
    print(e)


Combined dataset:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [4]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    this method finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value
    
    Parameters:
    - arr: input list or numpy array
    - threshold: numeric threshold for comparison
    - replacement_value: value to replace elements that meet the condition
    
    Returns:
    - modified_arr: numpy array with replacements
    """
    arr = np.array(arr)

    for i in range(arr.shape[0]):
        if arr[i] >= threshold:
            arr[i] = replacement_value
    
    return arr
    
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

data_input = input("Enter data: ")
data = list(map(int, data_input.split(',')))
threshold = int(input("Enter threshold: "))
replacement_value = int(input("Enter replacement value: "))
print("Original array:", data)
print("Modified array:", apply_threshold(data, threshold, replacement_value))

Original array: [1, 2, 3, 4, 5]
Modified array: [ 1 -1 -1 -1 -1]


TestCase

In [10]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])